# Generated by Django 4.2.2 on 2024-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image_file",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
