# Generated by Django 4.2.2 on 2024-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_item_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image_file",
            field=models.FileField(blank=True, upload_to="qr_code_files"),
        ),
    ]
