# Generated by Django 4.2.2 on 2024-05-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_item_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
