# Generated by Django 4.2.2 on 2024-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_item_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image_url",
            field=models.TextField(max_length=5000000, null=True),
        ),
    ]
